---


###########################################################################
# 6. 初始化主从复制（仅当存在从库时执行）
###########################################################################
- name: "等待主实例就绪"
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors:
      - "app={{ redis_name }}"
  register: redis_name
  until:
    - redis_pods.resources is defined
    - redis_pods.resources | length == redis_size | int * (redis_replicas | int + 1)
    - redis_pods.resources | map(attribute='status.phase') | unique | list == ["Running"]
  retries: 30
  delay: 10

- name: "初始化 Redis 集群"
  kubernetes.core.k8s_exec:
    namespace: "{{ namespace }}"
    pod: "{{ redis_name }}-0"
    command: |
      sh -c '
        REDIS_NODES=$(seq 0 $(({{ redis_size }}*({{ redis_replicas }}+1)-1)) | xargs -I{} echo {{ redis_name }}-{}.$(hostname -f | cut -d. -f2-):{{ redis_port }} | tr "\n" " ")
        redis-cli -a {{ redis_password }} --cluster create $REDIS_NODES --cluster-replicas {{ redis_replicas }} --cluster-yes
      '
  run_once: true
  register: cluster_init_result
  failed_when: "'OK' not in cluster_init_result.stdout"

