# 整个平台的命名空间
namespace: spring-boot

# Redis集群配置
redis_name: "redis-cluster"
redis_port: 6379
redis_nodeport: 30379
redis_cluster_enabled: ""
redis_host_path: "/data/redis"  # 所有节点需提前创建此目录
redis_image: "swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/redis:8.2.1"
redis_password: "Redis@123qwe"  # 集群密码
redis_storage_size: "10Gi"  # Redis存储大小