---
- name: 清理 Redis 资源
  ansible.builtin.command: >
    kubectl delete {{ item.kind }} {{ item.name }} -n {{ namespace }} --ignore-not-found=true
  loop:
    - kind: Deployment
      name: "{{ mysql_name }}"
    - kind: StatefulSet
      name: "{{ mysql_name }}"
    - kind: ReplicaSet
      name: "{{ mysql_name }}-.*"
    - kind: Service
      name: "{{ mysql_name }}-.*"
    - kind: ConfigMap
      name: "{{ mysql_name }}-.*"
    - kind: Secret
      name: "{{ mysql_name }}-.*"
    - kind: PersistentVolumeClaim
      name: "{{ mysql_name }}-.*"
    - kind: Job
      name: "{{ mysql_name }}-.*"
    - kind: PersistentVolumeClaim
      name: "{{ mysql_name }}-.*"
    - kind: PersistentVolume
      name: "{{ mysql_name }}-.*"
  failed_when: false
  run_once: true