---
#  在导入 init.sql 任务之后添加以下内容
- name: "显示 MySQL 初始账号密码信息"
  ansible.builtin.debug:
    msg:
      - "=================================================="
      - "连接端口：{{ mysql_nodeport }}"
      - "初始管理员账号：root"
      - "初始管理员密码：{{ mysql_root_password }}"
      - "=================================================="
  run_once: true
