---
- name: 输出部署结果摘要
  ansible.builtin.debug:
    msg:
      - "=================================================="
      - "部署模式：{{ app_mode }}（{{ app_nodes }}节点）"
      - "访问地址：http://任意K8s节点IP:{{ app_nodeport }}"
      - "=================================================="